version: '2.1'
volumes:
  postgres-db-data:
    driver: local

services:
  db:
    image: postgres:12
    restart: always
    hostname: db
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: habr
      POSTGRES_DB: habr_parser
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/pgdata

  django_admin:
    build: ./habr_admin
    depends_on:
      - db
    ports:
      - 8000:8000

  parser:
    build: ./habr_parser
    depends_on:
      - django_admin
